services:
  nginx-gateway:
    image: nginx:stable-alpine
    container_name: event_nginx_gateway
    ports:
      - "80:80"     # Ловит обычный HTTP
      - "443:443"   # Ловит защищенный HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - app-network
    depends_on:
      - events
      - auth
    restart: always

  events:
    image: event-space
    build:
      context: .
      dockerfile: ./apps/events/Dockerfile
    container_name: event_api_container
    ports:
      - "3000:3000"
    env_file:
      - env/.env.development
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - .:/usr/src/app/events
      - /usr/src/app/events/dist
  auth:
    image: auth-space
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    container_name: auth_api_container
    ports:
      - "3001:3001"
    env_file:
      - env/.env.development
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - .:/usr/src/app/auth
      - /usr/src/app/auth/dist

  payments:
    image: event-space
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
    container_name: event_api_container
    ports:
      - "3002:3002"
    env_file:
      - env/.env.development
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - .:/usr/src/app/payments
      - /usr/src/app/payments/dist

  db:
    image: postgres:15
    container_name: event_db_container
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - env/.env.development
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_space
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d event_space" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7-alpine
    container_name: event_redis_container
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - env/.env.development
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    volumes:
      - redis_data:/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_rules.yml:/etc/prometheus/prometheus_rules.yml
    ports:
      - "9090:9090"
    networks:
      - app-network
    depends_on:
      - events
      - auth
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3006:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network
    volumes:
      - grafana-storage:/var/lib/grafana
    links:
      - prometheus
    depends_on:
      - prometheus
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - app-network
    devices:
      - /dev/kmsg
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - app-network
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-network
  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger_container
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      app-network:
        aliases:
          - jaeger
  promtail:
    image: grafana/promtail:latest
    user: root
    environment:
      - DOCKER_API_VERSION=1.44
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app-network
volumes:
  postgres_data:
  redis_data:
  grafana-storage:
networks:
  app-network:
    driver: bridge